export const dummyTechtree = {
  physics: {
    nodes: [
      {
        id: 0,
        name: '선형대수',
        label: '선대',
        group: 2,
        recentMileage: [1, 2, 4, 5, 6],
        description:
          '비록 물리학과 전공과목은 아니지만, 양자역학을 제대로 이해하기 위해 수강하는것을 추천.',
      },
      {
        id: 1,
        name: '미적분학과벡터해석',
        label: '미적분',
        group: 1,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 2,
        name: '고급미적분학',
        label: '고미',
        group: 2,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 3,
        name: '현대물리',
        label: '현물',
        group: 2,
        recentMileage: [1, 2, 4, 5, 6],
        description: '현물1은 특수상대론. 현물2는 고체물리 겉핥기.',
      },
      {
        id: 4,
        name: '고전역학',
        label: '일역',
        group: 2,
        recentMileage: [1, 2, 4, 5, 6],
        core: true,
        description:
          '1학기때는 Simple Harmonic Oscillator와 라그랑지안 역학을, 2학기때는 강체와 coupled oscillation 을 배운다. ',
      },
      {
        id: 5,
        name: '열물리',
        label: '열',
        group: 3,
        recentMileage: [1, 2, 4, 5, 6],
        description:
          '통계물리와 겹치는 내용이 많아서, 열물리를 듣지않고 통계를 들어도 큰 문제는 없다. 겹치지 않는 내용(카르노 기관)들은 물리학과 입장에서 그다지 활용할 일 없는 내용이다.',
      },
      {
        id: 6,
        name: '통계물리',
        label: '통계',
        group: 3,
        recentMileage: [1, 2, 4, 5, 6],
        core: true,
      },
      {
        id: 7,
        name: '양자역학',
        label: '양자',
        group: 3,
        recentMileage: [1, 2, 4, 5, 6],
        core: true,
        description: '양자역학을 안배운 물리학과는 고등학교 4학년 5학년일뿐.',
      },
      {
        id: 8,
        name: '전자기학',
        label: '전자기',
        group: 3,
        recentMileage: [1, 2, 4, 5, 6],
        core: true,
      },
      {
        id: 9,
        name: '군론',
        label: '군론',
        group: 3,
        recentMileage: [1, 2, 4, 5, 6],
        description:
          '보통 수리물리 시간때 군론을 배우기는 하는데, 깊게 배우지는 않는다. 핵이나 입자에 관심있다면 따로 공부하는걸 권장',
      },
      {
        id: 10,
        name: '입자물리',
        label: '입자',
        group: 4,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 11,
        name: '핵물리',
        label: '핵',
        group: 4,
        recentMileage: [1, 2, 4, 5, 6],
        description: '쿼크모델 = 군론 이나 마찬가지라, 군론을 잘 공부했다면 보상받을 수 있다.',
      },
      {
        id: 12,
        name: '상대론',
        label: '상대론',
        group: 4,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 13,
        name: '광학',
        label: '광학',
        group: 4,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 14,
        name: '고체물리',
        label: '고체',
        group: 4,
        recentMileage: [1, 2, 4, 5, 6],
        description:
          '학부는 주로 Kittel 책을 사용하는데, 1학기때는 고체에 대한 기초 이론을, 2학기에는 고체에서 일어나는 여러 현상들에 대해 배운다.',
      },
      {
        id: 15,
        name: 'A1',
        label: 'A1',
        group: 4,
        recentMileage: [1, 2, 4, 5, 6],
        description:
          '2학년 전공이지만, 2학년때 보다는 4학년때 듣는걸 추천. 2학년때는 회로이론을 왜 배워야하는지 실감을 못하기 때문.',
      },
      {
        id: 16,
        name: 'B1',
        label: 'B1',
        group: 3,
        recentMileage: [1, 2, 4, 5, 6],
      },
    ],
    links: [
      {
        source: 0,
        target: 7,
        type: '',
      },
      {
        source: 0,
        target: 9,
        type: '',
      },
      {
        source: 1,
        target: 2,
        type: '',
      },
      {
        source: 1,
        target: 0,
        type: '',
      },
      {
        source: 2,
        target: 4,
        type: '',
      },
      {
        source: 2,
        target: 8,
        type: '',
      },
      {
        source: 3,
        target: 7,
        type: '',
      },
      {
        source: 3,
        target: 12,
        type: '',
      },
      {
        source: 4,
        target: 7,
        type: '',
      },
      {
        source: 5,
        target: 6,
        type: '',
      },
      {
        source: 6,
        target: 14,
        type: '',
      },
      {
        source: 7,
        target: 11,
        type: '',
      },

      {
        source: 7,
        target: 10,
        type: '',
      },
      {
        source: 7,
        target: 13,
        type: '',
      },
      {
        source: 7,
        target: 14,
        type: '',
      },
      {
        source: 8,
        target: 12,
        type: '',
      },
      {
        source: 8,
        target: 13,
        type: '',
      },
      {
        source: 8,
        target: 14,
        type: '',
      },
      {
        source: 9,
        target: 10,
        type: '',
      },
      {
        source: 9,
        target: 11,
        type: '',
      },
      {
        source: 9,
        target: 12,
        type: '',
      },
      {
        source: 1,
        target: 3,
        type: '',
      },
    ],
  },
  cs: {
    nodes: [
      {
        id: 0,
        name: '선형대수',
        label: '선형대수',
        group: 2,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 1,
        name: '공학수학',
        label: '공학수학',
        group: 1,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 2,
        name: '확률통계',
        label: '확률통계',
        group: 1,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 3,
        name: '컴퓨터그래픽스',
        label: '컴그',
        group: 4,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 4,
        name: '이산수학',
        label: '이산수학',
        group: 2,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 5,
        name: '객체지향프로그래밍',
        label: 'OOP',
        group: 1,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 6,
        name: '자료구조',
        label: '자료구조',
        group: 2,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 7,
        name: '컴퓨터프로그래밍',
        label: '컴프밍',
        group: 2,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 8,
        name: '프로그래밍언어구조',
        label: '프언구',
        group: 2,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 9,
        name: '컴파일러',
        label: '컴파일러',
        group: 3,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 10,
        name: '오토마타',
        label: '오토마타',
        group: 3,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 11,
        name: '논리회로설계',
        label: '논회설',
        group: 2,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 12,
        name: '알고리즘',
        label: '알고리즘',
        group: 2,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 13,
        name: 'HCI',
        label: 'HCI',
        group: 2,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 14,
        name: '인공지능',
        label: '인공지능',
        group: 2,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 15,
        name: '데이터마이닝',
        label: '데마',
        group: 3,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 16,
        name: '데이터베이스',
        label: 'DB',
        group: 2,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 17,
        name: '네트워크',
        label: '네트워크',
        group: 2,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 18,
        name: '인터넷프로그래밍',
        label: '인프밍',
        group: 2,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 19,
        name: '컴퓨터시스템',
        label: '컴시',
        group: 2,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 20,
        name: '운영체제',
        label: 'OS',
        group: 2,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 21,
        name: '시스템프로그래밍',
        label: '시프밍',
        group: 4,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 22,
        name: '멀티코어',
        label: '멀티코어',
        group: 4,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 23,
        name: '컴퓨터비전',
        label: '컴비전',
        group: 4,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 24,
        name: '머신러닝',
        label: '머신러닝',
        group: 4,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 25,
        name: '아키텍쳐',
        label: '아키텍쳐',
        group: 4,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 26,
        name: '정보보호',
        label: '정보보호',
        group: 4,
        recentMileage: [1, 2, 4, 5, 6],
      },
    ],
    links: [
      {
        source: 0,
        target: 24,
        type: '동시수강 가능?',
      },
      {
        source: 0,
        target: 23,
        type: '',
      },
      {
        source: 0,
        target: 3,
        type: '동시수강 가능??',
      },
      {
        source: 2,
        target: 23,
        type: '',
      },
      {
        source: 2,
        target: 14,
        type: '',
      },
      {
        source: 6,
        target: 24,
        type: '',
      },
      {
        source: 6,
        target: 14,
        type: '',
      },
      {
        source: 6,
        target: 12,
        type: '',
      },
      {
        source: 6,
        target: 11,
        type: '',
      },
      {
        source: 6,
        target: 10,
        type: '',
      },
      {
        source: 6,
        target: 15,
        type: '',
      },
      {
        source: 6,
        target: 20,
        type: '',
      },
      {
        source: 6,
        target: 19,
        type: '',
      },
      {
        source: 5,
        target: 6,
        type: '',
      },
      {
        source: 1,
        target: 23,
        type: '',
      },
      {
        source: 7,
        target: 5,
        type: '',
      },
      {
        source: 4,
        target: 10,
        type: '',
      },
      {
        source: 4,
        target: 11,
        type: '',
      },
      {
        source: 4,
        target: 12,
        type: '',
      },
      {
        source: 17,
        target: 26,
        type: '',
      },
      {
        source: 19,
        target: 26,
        type: '',
      },
      {
        source: 18,
        target: 16,
        type: '',
      },
      {
        source: 16,
        target: 26,
        type: '',
      },
      {
        source: 19,
        target: 25,
        type: '',
      },
      {
        source: 25,
        target: 22,
        type: '',
      },
      {
        source: 20,
        target: 21,
        type: '',
      },
    ],
  },
  politics: {
    nodes: [
      {
        id: 0,
        name: '사회과학조사방법론',

        group: 1,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 1,
        name: '정치학데이터분석',

        group: 1,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 2,
        name: '정치분석연습',

        group: 1,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 3,
        name: '정치이론입문',

        group: 1,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 4,
        name: '정치이론과철학',
        group: 1,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 5,
        name: '정의론',
        group: 1,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 6,
        name: '국제정의론',
        group: 1,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 7,
        name: '페미니스트정치이론',
        group: 1,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 8,
        name: 'Theories of Democracy',
        group: 1,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 9,
        name: 'Ancient & Medival Western Political Thought',
        group: 1,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 10,
        name: '동양정치사상',
        group: 1,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 11,
        name: '한국정치사상',
        group: 1,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 12,
        name: '고대중세서양정치사상',
        group: 1,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 13,
        name: '근대서양정치사상',
        group: 1,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 14,
        name: '탈근대정치사상',
        group: 1,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 15,
        name: '국가론',
        group: 1,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 16,
        name: '권력구조론',
        group: 1,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 17,
        name: '법의철학적기초',
        group: 1,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 18,
        name: '외교의이론과실제',
        group: 1,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 19,
        name: '민족주의이론과실제',
        group: 1,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 20,
        name: '민족분쟁론',
        group: 1,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 21,
        name: '비교정치론',
        group: 2,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 22,
        name: '비교정치체제론',
        group: 2,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 23,
        name: '비교헌정연구',
        group: 2,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 24,
        name: '권력구조론',
        group: 2,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 25,
        name: '대통령리더쉽론',
        group: 2,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 26,
        name: '일본정치와외교',
        group: 2,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 27,
        name: '일본과동아시아',
        group: 2,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 28,
        name: '중국정치의이해',
        group: 2,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 29,
        name: '러시아정치',
        group: 2,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 30,
        name: '미국정치',
        group: 2,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 31,
        name: '미국정치사상',
        group: 2,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 32,
        name: 'United States Foreign Policy',
        group: 2,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 33,
        name: 'American Government and Politics',
        group: 2,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 34,
        name: '중동정치',
        group: 2,
        recentMileage: [1, 2, 4, 5, 6],
      },

      {
        id: 35,
        name: '한국정치사',
        group: 3,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 36,
        name: '한국정치사상',
        group: 3,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 37,
        name: '한국정치론',
        group: 3,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 38,
        name: '정당론',
        group: 3,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 39,
        name: '한국의정치경제',
        group: 3,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 40,
        name: '한국외교정책',
        group: 3,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 41,
        name: '한국국제정치사',
        group: 3,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 42,
        name: '한국과동아시아국제관계사',
        group: 3,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 43,
        name: '법의철학적기초',
        group: 3,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 44,
        name: '법과정치',
        group: 3,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 45,
        name: '국가와헌법',
        group: 3,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 46,
        name: '한국풀뿌리민주주의탐색',
        group: 3,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 47,
        name: '한반도통일정책론',
        group: 3,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 48,
        name: '북한외교정책',
        group: 3,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 49,
        name: 'North Korean Politics & Foreign Policy',
        group: 3,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 50,
        name: '전쟁과평화',
        group: 4,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 51,
        name: '국제관계론',
        group: 4,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 52,
        name: '국제정의론',
        group: 4,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 53,
        name: '한국국제정치사',
        group: 4,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 54,
        name: '한국과동아시아국제관계사',
        group: 4,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 55,
        name: '북한외교정책',
        group: 4,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 56,
        name: '동북아시아국제관계',
        group: 4,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 57,
        name: '동아시아국제관계',
        group: 4,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 58,
        name: '동북아국제안보',
        group: 4,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 59,
        name: '국가안보와정보',
        group: 4,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 60,
        name: '핵무기와국제정치',
        group: 4,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 61,
        name: '외교정책론',
        group: 4,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 62,
        name: '외교안보와미디어',
        group: 4,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 63,
        name: '외교의이론과실제',
        group: 4,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 64,
        name: '합리적선택과안보',
        group: 4,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 65,
        name: '국제법',
        group: 4,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 66,
        name: '국제법과국제관계',
        group: 4,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 67,
        name: '국제법과국제기구',
        group: 4,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 68,
        name: '국제기구론',
        group: 4,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 69,
        name: '국제개발협력과EU',
        group: 4,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 70,
        name: 'Politics Media and Globalization',
        group: 4,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 71,
        name: 'Politics of Colaboration and Integration',
        group: 4,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 72,
        name: 'Cosmopolitanism and Critics',
        group: 4,
        recentMileage: [1, 2, 4, 5, 6],
      },
      {
        id: 73,
        name: 'International Security',
        group: 4,
        recentMileage: [1, 2, 4, 5, 6],
      },
    ],
    links: [],
  },
}
