export const dummyTechtreeDataList = [
  {
    id: '1234567890qwertyuiop1234',
    title: '실험용 테크트리1',
    nodeList: [
      {
        id: 'asdfasdfasdfasdfasdfasdf',
        name: '첫번째 노드',
        x: 150,
        y: 150,
        radius: 15,
        body: '## 이것은 마크다운.\n실험용 첫번째 노드',
        tag: '프론트엔드',
        fillColor: '#91a7ff',
      },
      {
        id: 'bbdfasdfasdfasdfasdfasdf',
        name: '두번째 노드',
        x: 300,
        y: 200,
        radius: 15,
        body: 'x랑 y의 값은 둘다 300임. 두번째 노드임',
        tag: '백엔드',
        fillColor: '#339af0',
      },
    ],
    linkList: [
      {
        startNodeID: 'asdfasdfasdfasdfasdfasdf',
        endNodeID: 'bbdfasdfasdfasdfasdfasdf',
        startX: 150,
        startY: 150,
        endX: 300,
        endY: 200,
        id: 'ccdfasdfasdfasdfasdfasdf',
        left: false,
        right: true,
      },
    ],
  },
  {
    id: '1234567890qwertyuiop1235',
    title: '실험용 테크트리2',
    nodeList: [
      {
        id: 'asdfasdfasdfasdfasdfasdf',
        name: '첫번째 노드',
        x: 150,
        y: 150,
        radius: 15,
        body: '## 이것은 마크다운.\n실험용 첫번째 노드',
        tag: '프론트엔드',
        fillColor: '#91a7ff',
      },
      {
        id: 'bbdfasdfasdfasdfasdfasdf',
        name: '두번째 노드',
        x: 300,
        y: 400,
        radius: 15,
        body: 'x랑 y의 값은 둘다 300임. 두번째 노드임',
        tag: '백엔드',
        fillColor: '#339af0',
      },
      {
        id: 'bbdfasdfasdfasdfasdfasdf',
        name: 'Javascript',
        x: 444,
        y: 166,
        radius: 15,
        body: '세번째 노드',
        hashtags: ['백엔드'],
        fillColor: '#339af0',
      },
      {
        id: 'bbdfasdfasdfasdfasdfasdf',
        name: 'Typescript',
        x: 536,
        y: 233,
        radius: 15,
        body: 'x랑 y의 값은 둘다 300임. 두번째 노드임',
        tag: '백엔드',
        fillColor: '#339af0',
      },
      {
        id: 'bbdfasdfasdfasdfasdfasdf',
        name: 'React',
        x: 519,
        y: 404,
        radius: 15,
        body: 'x랑 y의 값은 둘다 300임. 두번째 노드임',
        tag: '백엔드',
        fillColor: '#339af0',
      },
    ],
    linkList: [
      {
        startNodeID: 'asdfasdfasdfasdfasdfasdf',
        endNodeID: 'bbdfasdfasdfasdfasdfasdf',
        startX: 150,
        startY: 150,
        endX: 300,
        endY: 400,
        id: 'ccdfasdfasdfasdfasdfasdf',
        left: false,
        right: true,
      },
    ],
  },
  {
    id: '1234567890qwertyuiop1236',
    title: '실험용 테크트리3',
    nodeList: [
      {
        id: 'asdfasdfasdfasdfasdfasdf',
        name: '첫번째 노드',
        x: 150,
        y: 150,
        radius: 15,
        body: '## 이것은 마크다운.\n실험용 첫번째 노드',
        tag: '프론트엔드',
        fillColor: '#91a7ff',
      },
      {
        id: 'bbdfasdfasdfasdfasdfasdf',
        name: '두번째 노드',
        x: 300,
        y: 300,
        radius: 15,
        body: 'x랑 y의 값은 둘다 300임. 두번째 노드임',
        tag: '백엔드',
        fillColor: '#339af0',
      },
    ],
    linkList: [
      {
        startNodeID: 'asdfasdfasdfasdfasdfasdf',
        endNodeID: 'bbdfasdfasdfasdfasdfasdf',
        startX: 150,
        startY: 150,
        endX: 300,
        endY: 300,
        id: 'ccdfasdfasdfasdfasdfasdf',
        left: false,
        right: true,
      },
    ],
  },
  {
    id: '1234567890qwertyuiop1237',
    title: '실험용 테크트리4',
    nodeList: [
      {
        id: 'asdfasdfasdfasdfasdfasdf',
        name: '첫번째 노드',
        x: 150,
        y: 150,
        radius: 15,
        body: '## 이것은 마크다운.\n실험용 첫번째 노드',
        tag: '프론트엔드',
        fillColor: '#91a7ff',
      },
      {
        id: 'bbdfasdfasdfasdfasdfasdf',
        name: '두번째 노드',
        x: 300,
        y: 300,
        radius: 15,
        body: 'x랑 y의 값은 둘다 300임. 두번째 노드임',
        tag: '백엔드',
        fillColor: '#339af0',
      },
    ],
    linkList: [
      {
        startNodeID: 'asdfasdfasdfasdfasdfasdf',
        endNodeID: 'bbdfasdfasdfasdfasdfasdf',
        startX: 150,
        startY: 150,
        endX: 300,
        endY: 300,
        id: 'ccdfasdfasdfasdfasdfasdf',
        left: false,
        right: true,
      },
    ],
  },
  {
    id: '1234567890qwertyuiop1238',
    title: '실험용 테크트리5',
    nodeList: [
      {
        id: 'asdfasdfasdfasdfasdfasdf',
        name: '첫번째 노드',
        x: 150,
        y: 150,
        radius: 15,
        body: '## 이것은 마크다운.\n실험용 첫번째 노드',
        tag: '프론트엔드',
        fillColor: '#91a7ff',
      },
      {
        id: 'bbdfasdfasdfasdfasdfasdf',
        name: '두번째 노드',
        x: 300,
        y: 300,
        radius: 15,
        body: 'x랑 y의 값은 둘다 300임. 두번째 노드임',
        tag: '백엔드',
        fillColor: '#339af0',
      },
    ],
    linkList: [
      {
        startNodeID: 'asdfasdfasdfasdfasdfasdf',
        endNodeID: 'bbdfasdfasdfasdfasdfasdf',
        startX: 150,
        startY: 150,
        endX: 300,
        endY: 300,
        id: 'ccdfasdfasdfasdfasdfasdf',
        left: false,
        right: true,
      },
    ],
  },
  {
    id: '1234567890qwertyuiop1239',
    title: '실험용 테크트리',
    nodeList: [
      {
        id: 'asdfasdfasdfasdfasdfasdf',
        name: '첫번째 노드',
        x: 150,
        y: 150,
        radius: 15,
        body: '## 이것은 마크다운.\n실험용 첫번째 노드',
        tag: '프론트엔드',
        fillColor: '#91a7ff',
      },
      {
        id: 'bbdfasdfasdfasdfasdfasdf',
        name: '두번째 노드',
        x: 300,
        y: 300,
        radius: 15,
        body: 'x랑 y의 값은 둘다 300임. 두번째 노드임',
        tag: '백엔드',
        fillColor: '#339af0',
      },
    ],
    linkList: [
      {
        startNodeID: 'asdfasdfasdfasdfasdfasdf',
        endNodeID: 'bbdfasdfasdfasdfasdfasdf',
        startX: 150,
        startY: 150,
        endX: 300,
        endY: 300,
        id: 'ccdfasdfasdfasdfasdfasdf',
        left: false,
        right: true,
      },
    ],
  },
  {
    id: '1234567890qwertyuiop1230',
    title: '실험용 테크트리',
    nodeList: [
      {
        id: 'asdfasdfasdfasdfasdfasdf',
        name: '첫번째 노드',
        x: 150,
        y: 150,
        radius: 15,
        body: '## 이것은 마크다운.\n실험용 첫번째 노드',
        tag: '프론트엔드',
        fillColor: '#91a7ff',
      },
      {
        id: 'bbdfasdfasdfasdfasdfasdf',
        name: '두번째 노드',
        x: 300,
        y: 300,
        radius: 15,
        body: 'x랑 y의 값은 둘다 300임. 두번째 노드임',
        tag: '백엔드',
        fillColor: '#339af0',
      },
    ],
    linkList: [
      {
        startNodeID: 'asdfasdfasdfasdfasdfasdf',
        endNodeID: 'bbdfasdfasdfasdfasdfasdf',
        startX: 150,
        startY: 150,
        endX: 300,
        endY: 300,
        id: 'ccdfasdfasdfasdfasdfasdf',
        left: false,
        right: true,
      },
    ],
  },
  {
    id: '1234567890qwertyuiop1233',
    title: '실험용 테크트리',
    nodeList: [
      {
        id: 'asdfasdfasdfasdfasdfasdf',
        name: '첫번째 노드',
        x: 150,
        y: 150,
        radius: 15,
        body: '## 이것은 마크다운.\n실험용 첫번째 노드',
        tag: '프론트엔드',
        fillColor: '#91a7ff',
      },
      {
        id: 'bbdfasdfasdfasdfasdfasdf',
        name: '두번째 노드',
        x: 300,
        y: 300,
        radius: 15,
        body: 'x랑 y의 값은 둘다 300임. 두번째 노드임',
        tag: '백엔드',
        fillColor: '#339af0',
      },
    ],
    linkList: [
      {
        startNodeID: 'asdfasdfasdfasdfasdfasdf',
        endNodeID: 'bbdfasdfasdfasdfasdfasdf',
        startX: 150,
        startY: 150,
        endX: 300,
        endY: 300,
        id: 'ccdfasdfasdfasdfasdfasdf',
        left: false,
        right: true,
      },
    ],
  },
  {
    id: '1234567890qwertyuiop1232',
    title: '실험용 테크트리',
    nodeList: [
      {
        id: 'asdfasdfasdfasdfasdfasdf',
        name: '첫번째 노드',
        x: 150,
        y: 150,
        radius: 15,
        body: '## 이것은 마크다운.\n실험용 첫번째 노드',
        tag: '프론트엔드',
        fillColor: '#91a7ff',
      },
      {
        id: 'bbdfasdfasdfasdfasdfasdf',
        name: '두번째 노드',
        x: 300,
        y: 300,
        radius: 15,
        body: 'x랑 y의 값은 둘다 300임. 두번째 노드임',
        tag: '백엔드',
        fillColor: '#339af0',
      },
    ],
    linkList: [
      {
        startNodeID: 'asdfasdfasdfasdfasdfasdf',
        endNodeID: 'bbdfasdfasdfasdfasdfasdf',
        startX: 150,
        startY: 150,
        endX: 300,
        endY: 300,
        id: 'ccdfasdfasdfasdfasdfasdf',
        left: false,
        right: true,
      },
    ],
  },
  {
    id: '1234567890qwertyuiop1231',
    title: '실험용 테크트리',
    nodeList: [
      {
        id: 'asdfasdfasdfasdfasdfasdf',
        name: '첫번째 노드',
        x: 150,
        y: 150,
        radius: 15,
        body: '## 이것은 마크다운.\n실험용 첫번째 노드',
        tag: '프론트엔드',
        fillColor: '#91a7ff',
      },
      {
        id: 'bbdfasdfasdfasdfasdfasdf',
        name: '두번째 노드',
        x: 300,
        y: 300,
        radius: 15,
        body: 'x랑 y의 값은 둘다 300임. 두번째 노드임',
        tag: '백엔드',
        fillColor: '#339af0',
      },
    ],
    linkList: [
      {
        startNodeID: 'asdfasdfasdfasdfasdfasdf',
        endNodeID: 'bbdfasdfasdfasdfasdfasdf',
        startX: 150,
        startY: 150,
        endX: 300,
        endY: 300,
        id: 'ccdfasdfasdfasdfasdfasdf',
        left: false,
        right: true,
      },
    ],
  },
  {
    id: '1234567890qwertyuiop123a',
    title: '실험용 테크트리',
    nodeList: [
      {
        id: 'asdfasdfasdfasdfasdfasdf',
        name: '첫번째 노드',
        x: 150,
        y: 150,
        radius: 15,
        body: '## 이것은 마크다운.\n실험용 첫번째 노드',
        tag: '프론트엔드',
        fillColor: '#91a7ff',
      },
      {
        id: 'bbdfasdfasdfasdfasdfasdf',
        name: '두번째 노드',
        x: 300,
        y: 300,
        radius: 15,
        body: 'x랑 y의 값은 둘다 300임. 두번째 노드임',
        tag: '백엔드',
        fillColor: '#339af0',
      },
    ],
    linkList: [
      {
        startNodeID: 'asdfasdfasdfasdfasdfasdf',
        endNodeID: 'bbdfasdfasdfasdfasdfasdf',
        startX: 150,
        startY: 150,
        endX: 300,
        endY: 300,
        id: 'ccdfasdfasdfasdfasdfasdf',
        left: false,
        right: true,
      },
    ],
  },
  {
    id: '1234567890qwertyuiop123b',
    title: '실험용 테크트리',
    nodeList: [
      {
        id: 'asdfasdfasdfasdfasdfasdf',
        name: '첫번째 노드',
        x: 150,
        y: 150,
        radius: 15,
        body: '## 이것은 마크다운.\n실험용 첫번째 노드',
        tag: '프론트엔드',
        fillColor: '#91a7ff',
      },
      {
        id: 'bbdfasdfasdfasdfasdfasdf',
        name: '두번째 노드',
        x: 300,
        y: 300,
        radius: 15,
        body: 'x랑 y의 값은 둘다 300임. 두번째 노드임',
        tag: '백엔드',
        fillColor: '#339af0',
      },
    ],
    linkList: [
      {
        startNodeID: 'asdfasdfasdfasdfasdfasdf',
        endNodeID: 'bbdfasdfasdfasdfasdfasdf',
        startX: 150,
        startY: 150,
        endX: 300,
        endY: 300,
        id: 'ccdfasdfasdfasdfasdfasdf',
        left: false,
        right: true,
      },
    ],
  },
  {
    id: '1234567890qwertyuiop123c',
    title: '실험용 테크트리5',
    nodeList: [
      {
        id: 'asdfasdfasdfasdfasdfasdf',
        name: '첫번째 노드',
        x: 150,
        y: 150,
        radius: 15,
        body: '## 이것은 마크다운.\n실험용 첫번째 노드',
        tag: '프론트엔드',
        fillColor: '#91a7ff',
      },
      {
        id: 'bbdfasdfasdfasdfasdfasdf',
        name: '두번째 노드',
        x: 300,
        y: 300,
        radius: 15,
        body: 'x랑 y의 값은 둘다 300임. 두번째 노드임',
        tag: '백엔드',
        fillColor: '#339af0',
      },
    ],
    linkList: [
      {
        startNodeID: 'asdfasdfasdfasdfasdfasdf',
        endNodeID: 'bbdfasdfasdfasdfasdfasdf',
        startX: 150,
        startY: 150,
        endX: 300,
        endY: 300,
        id: 'ccdfasdfasdfasdfasdfasdf',
        left: false,
        right: true,
      },
    ],
  },
  {
    id: '1234567890qwertyuiop123d',
    title: '실험용 테크트리',
    nodeList: [
      {
        id: 'asdfasdfasdfasdfasdfasdf',
        name: '첫번째 노드',
        x: 150,
        y: 150,
        radius: 15,
        body: '## 이것은 마크다운.\n실험용 첫번째 노드',
        tag: '프론트엔드',
        fillColor: '#91a7ff',
      },
      {
        id: 'bbdfasdfasdfasdfasdfasdf',
        name: '두번째 노드',
        x: 300,
        y: 300,
        radius: 15,
        body: 'x랑 y의 값은 둘다 300임. 두번째 노드임',
        tag: '백엔드',
        fillColor: '#339af0',
      },
    ],
    linkList: [
      {
        startNodeID: 'asdfasdfasdfasdfasdfasdf',
        endNodeID: 'bbdfasdfasdfasdfasdfasdf',
        startX: 150,
        startY: 150,
        endX: 300,
        endY: 300,
        id: 'ccdfasdfasdfasdfasdfasdf',
        left: false,
        right: true,
      },
    ],
  },
  {
    id: '1234567890qwertyuiop123e',
    title: '실험용 테크트리',
    nodeList: [
      {
        id: 'asdfasdfasdfasdfasdfasdf',
        name: '첫번째 노드',
        x: 150,
        y: 150,
        radius: 15,
        body: '## 이것은 마크다운.\n실험용 첫번째 노드',
        tag: '프론트엔드',
        fillColor: '#91a7ff',
      },
      {
        id: 'bbdfasdfasdfasdfasdfasdf',
        name: '두번째 노드',
        x: 300,
        y: 300,
        radius: 15,
        body: 'x랑 y의 값은 둘다 300임. 두번째 노드임',
        tag: '백엔드',
        fillColor: '#339af0',
      },
    ],
    linkList: [
      {
        startNodeID: 'asdfasdfasdfasdfasdfasdf',
        endNodeID: 'bbdfasdfasdfasdfasdfasdf',
        startX: 150,
        startY: 150,
        endX: 300,
        endY: 300,
        id: 'ccdfasdfasdfasdfasdfasdf',
        left: false,
        right: true,
      },
    ],
  },
  {
    id: '1234567890qwertyuiop123f',
    title: '실험용 테크트리',
    nodeList: [
      {
        id: 'asdfasdfasdfasdfasdfasdf',
        name: '첫번째 노드',
        x: 150,
        y: 150,
        radius: 15,
        body: '## 이것은 마크다운.\n실험용 첫번째 노드',
        tag: '프론트엔드',
        fillColor: '#91a7ff',
      },
      {
        id: 'bbdfasdfasdfasdfasdfasdf',
        name: '두번째 노드',
        x: 300,
        y: 300,
        radius: 15,
        body: 'x랑 y의 값은 둘다 300임. 두번째 노드임',
        tag: '백엔드',
        fillColor: '#339af0',
      },
    ],
    linkList: [
      {
        startNodeID: 'asdfasdfasdfasdfasdfasdf',
        endNodeID: 'bbdfasdfasdfasdfasdfasdf',
        startX: 150,
        startY: 150,
        endX: 300,
        endY: 300,
        id: 'ccdfasdfasdfasdfasdfasdf',
        left: false,
        right: true,
      },
    ],
  },
  {
    id: '1234567890qwertyuiop123g',
    title: '실험용 테크트리',
    nodeList: [
      {
        id: 'asdfasdfasdfasdfasdfasdf',
        name: '첫번째 노드',
        x: 150,
        y: 150,
        radius: 15,
        body: '## 이것은 마크다운.\n실험용 첫번째 노드',
        tag: '프론트엔드',
        fillColor: '#91a7ff',
      },
      {
        id: 'bbdfasdfasdfasdfasdfasdf',
        name: '두번째 노드',
        x: 300,
        y: 300,
        radius: 15,
        body: 'x랑 y의 값은 둘다 300임. 두번째 노드임',
        tag: '백엔드',
        fillColor: '#339af0',
      },
    ],
    linkList: [
      {
        startNodeID: 'asdfasdfasdfasdfasdfasdf',
        endNodeID: 'bbdfasdfasdfasdfasdfasdf',
        startX: 150,
        startY: 150,
        endX: 300,
        endY: 300,
        id: 'ccdfasdfasdfasdfasdfasdf',
        left: false,
        right: true,
      },
    ],
  },
  {
    id: '1234567890qwertyuiop123h',
    title: '실험용 테크트리',
    nodeList: [
      {
        id: 'asdfasdfasdfasdfasdfasdf',
        name: '첫번째 노드',
        x: 150,
        y: 150,
        radius: 15,
        body: '## 이것은 마크다운.\n실험용 첫번째 노드',
        tag: '프론트엔드',
        fillColor: '#91a7ff',
      },
      {
        id: 'bbdfasdfasdfasdfasdfasdf',
        name: '두번째 노드',
        x: 300,
        y: 300,
        radius: 15,
        body: 'x랑 y의 값은 둘다 300임. 두번째 노드임',
        tag: '백엔드',
        fillColor: '#339af0',
      },
    ],
    linkList: [
      {
        startNodeID: 'asdfasdfasdfasdfasdfasdf',
        endNodeID: 'bbdfasdfasdfasdfasdfasdf',
        startX: 150,
        startY: 150,
        endX: 300,
        endY: 300,
        id: 'ccdfasdfasdfasdfasdfasdf',
        left: false,
        right: true,
      },
    ],
  },
  {
    id: '1234567890qwertyuiop123i',
    title: '실험용 테크트리',
    nodeList: [
      {
        id: 'asdfasdfasdfasdfasdfasdf',
        name: '첫번째 노드',
        x: 150,
        y: 150,
        radius: 15,
        body: '## 이것은 마크다운.\n실험용 첫번째 노드',
        tag: '프론트엔드',
        fillColor: '#91a7ff',
      },
      {
        id: 'bbdfasdfasdfasdfasdfasdf',
        name: '두번째 노드',
        x: 300,
        y: 300,
        radius: 15,
        body: 'x랑 y의 값은 둘다 300임. 두번째 노드임',
        tag: '백엔드',
        fillColor: '#339af0',
      },
    ],
    linkList: [
      {
        startNodeID: 'asdfasdfasdfasdfasdfasdf',
        endNodeID: 'bbdfasdfasdfasdfasdfasdf',
        startX: 150,
        startY: 150,
        endX: 300,
        endY: 300,
        id: 'ccdfasdfasdfasdfasdfasdf',
        left: false,
        right: true,
      },
    ],
  },
  {
    id: '1234567890qwertyuiop123j',
    title: '실험용 테크트리',
    nodeList: [
      {
        id: 'asdfasdfasdfasdfasdfasdf',
        name: '첫번째 노드',
        x: 150,
        y: 150,
        radius: 15,
        body: '## 이것은 마크다운.\n실험용 첫번째 노드',
        tag: '프론트엔드',
        fillColor: '#91a7ff',
      },
      {
        id: 'bbdfasdfasdfasdfasdfasdf',
        name: '두번째 노드',
        x: 300,
        y: 300,
        radius: 15,
        body: 'x랑 y의 값은 둘다 300임. 두번째 노드임',
        tag: '백엔드',
        fillColor: '#339af0',
      },
    ],
    linkList: [
      {
        startNodeID: 'asdfasdfasdfasdfasdfasdf',
        endNodeID: 'bbdfasdfasdfasdfasdfasdf',
        startX: 150,
        startY: 150,
        endX: 300,
        endY: 300,
        id: 'ccdfasdfasdfasdfasdfasdf',
        left: false,
        right: true,
      },
    ],
  },
]
